// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// During build phase, DATABASE_URL may not be available
// Prisma generate only needs the schema file, not the database connection
// Use try-catch to handle missing DATABASE_URL gracefully
let databaseUrl: string;
try {
  databaseUrl = env("DATABASE_URL");
} catch (error) {
  // During build, DATABASE_URL is not required for prisma generate
  databaseUrl = "postgresql://placeholder@localhost:5432/placeholder";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
